name: fataak
description: "A grocery delivery app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for modern Dart

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # UI & UX
  carousel_slider: ^4.2.1 # Updated to latest
  badges: ^3.1.2
  cached_network_image: ^3.3.1 # Added for lazy loading
  shimmer: ^3.0.0 # Added for skeleton loading

  # Utilities
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Updated to latest

flutter:
  uses-material-design: true
  assets:
    - assets/images/